top_srcdir              ?= ../../..

include $(top_srcdir)/include/mk/env_pre.mk

MAKE_TARGETS :=

SUBDIRS := src/rpmsg_rpc src/kernel/modules

include $(top_srcdir)/include/mk/generic_trunk_target.mk

